#!/bin/bash
#PBS -l nodes=1:ppn=8,vmem=31gb,walltime=15:00:00
#PBS -N ensembletracking
#PBS -V

#make the script to fail if any of the commands ran fails.
set -e

time singularity exec -e docker://mandymejia/clever:1.5 Rscript main.R
