#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=15:00:00
#PBS -N ensembletracking
#PBS -V

#make the script to fail if any of the commands ran fails.
set -e

bold=$(jq -r '.bold' config.json)

time singularity exec -e docker://brainlife/clever:1.0 Rscript main.R $bold

